#this script is generated by the DMV A97 Application Inventory to enumerate members of an AD group and add them to a table in SQL Server

$servername = "devdbaot"
$dbname = "MigrateDMVa97"
$adGroupid = 114

$adGroup ="DMV-Database P & U Tax Exempt View Only"
$counter = 0
$output = ""

$objectclassid = 0
$unhandledobjectclass = ""

$users = Get-ADGroupMember $adGroup -recursive
foreach ($user in $users) {

	Switch ($user.objectClass) {
		'user' {$objectclassid = 1}
		'group' {$objectclassid = 2}
		default {
			$unhandledobjectclass =  $unhandledobjectclass + $user.objectclass + ", "
			$objectclassid = 0
			}
		}

	$sql ="INSERT INTO tblADmember (adgroupid,objectclassid,membername) VALUES ($adGroupid,$objectclassid,'" + $user.name + "');"
	invoke-sqlcmd -ServerInstance $servername -Database $dbname -Query $sql | Out-Null

	$counter = $counter + 1
	$output = $output + $User.name + ", "

}
Write-Host $counter " record(s) inserted into tblADmember: " $output
if ($unhandledobjectclass -ne ""){Write-Host "Unhandled object class(es): " $unhandledobjectclass}


